### ISSUE TITLE
Parelization of multiple poses

### ISSUE THREAD

**Issue by joao-pm-santos96** [joao-pm-santos96/SmObEx#22]

**Comment by joao-pm-santos96** [comment]
Is it possible to parallelize an simple action server action. the only thing stopping at this point is move group ..?

**Comment by miguelriemoliveira** [comment]
Yes, I believe so, you just have to launch a thread to handle the processing of each goal, and accept all of them.

Take a look at the action server example I was doing with Tiago Tavares

https://github.com/miguelriemoliveira/my-action-server

The problem is that this is in python, but he said he could do one in cpp ...

**Comment by miguelriemoliveira** [comment]
or perhaps you can use the python code and use cpp only for the octomap stuff ...

**Comment by joao-pm-santos96** [comment]
Yeah maybe.. but the problem is in the MoveIt action itself not the one that will be create

**Comment by miguelriemoliveira** [comment]
I see, then perhaps it is impossible without rewritting the moveit code
itself.

*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by joao-pm-santos96** [comment]
not needed anymore
